In [1]:
from datetime import datetime

In [2]:
string_datetime = '10:25:30 2021-02-20'
string_datetime

'10:25:30 2021-02-20'

In [3]:
type(string_datetime)

str

In [4]:
my_first_datetime = datetime.strptime(string_datetime, '%H:%M:%S %Y-%m-%d')
my_first_datetime

datetime.datetime(2021, 2, 20, 10, 25, 30)

###  pd.to_datetime(): Converting Data into datetime Objects

In [5]:
import pandas as pd

In [6]:
my_new_datetime = pd.to_datetime(string_datetime, format = '%H:%M:%S %Y-%m-%d')
my_new_datetime

Timestamp('2021-02-20 10:25:30')

In [7]:
type(my_new_datetime)

pandas._libs.tslibs.timestamps.Timestamp

In [8]:
# without the "format" parameter:
my_new_datetime = pd.to_datetime(string_datetime)
my_new_datetime

Timestamp('2021-02-20 10:25:30')

In [9]:
my_new_datetime.hour

10

In [10]:
my_new_datetime.minute

25

In [11]:
my_new_datetime.second

30

In [12]:
my_new_datetime.year

2021

In [13]:
my_new_datetime.month

2

In [14]:
my_new_datetime.day

20

In [15]:
data = pd.read_csv('Lending-company.csv', index_col = 'LoanID')
lending_co_data = data.copy()
lending_co_data.head()

,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
LoanID,,,,,,,,,,,,,,
1,LoanID_1,Product B,Male,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
2,LoanID_2,Product B,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
3,LoanID_3,Product C,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
4,LoanID_4,Product B,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
5,LoanID_5,Product D,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [16]:
# we are interested in 'StartDate'
lending_co_data['StartDate'].head()

LoanID
1    04/07/2018
2    02/01/2019
3    08/12/2016
4           NaN
5    28/10/2017
Name: StartDate, dtype: object

In [17]:
pd.to_datetime(lending_co_data['StartDate'])

LoanID
1      2018-04-07
2      2019-02-01
3      2016-08-12
4             NaT
5      2017-10-28
          ...
1039   2018-12-29
1040   2018-03-28
1041   2018-04-26
1042   2016-10-25
1043   2019-05-15
Name: StartDate, Length: 1043, dtype: datetime64[ns]

In [18]:
lending_co_data['StartDate'] = pd.to_datetime(lending_co_data['StartDate'])
lending_co_data.head()

,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
LoanID,,,,,,,,,,,,,,
1,LoanID_1,Product B,Male,Location 3,Region 2,17600.0,2018-04-07,2200,45,365,3221,4166,14621,Active
2,LoanID_2,Product B,Female,Location 6,Region 6,NaN,2019-02-01,2200,45,365,3161,4096,16041,Active
3,LoanID_3,Product C,Male,Location 8,Region 3,16600.0,2016-08-12,1000,45,365,2260,3205,16340,NaN
4,LoanID_4,Product B,Male,Location 26,Region 2,17600.0,NaT,2200,45,365,3141,4166,16321,Active
5,LoanID_5,Product D,Female,Location 34,Region 3,21250.0,2017-10-28,2200,55,365,3570,4745,14720,Active